### ISSUE TITLE
Issue displaying SonarQube widget

### ISSUE THREAD

**Issue by wflentje** [red6/atlasboard-red6-package#1]
Hello,

Getting following error when trying to display SonarQube widget.

ReferenceError: md5 is not defined
 app.js line 1 > eval:10:1

![sonar](https://cloud.githubusercontent.com/assets/16246317/12364539/71bb521a-bb8c-11e5-801e-d7210eff52dd.png)

Tried:

C:\Users\V808278\Downloads\atlas\dashboardb>npm install md5@2.x
npm WARN package.json require.async@0.1.1 No repository field.
md5@2.0.0 node_modules\md5
├── crypt@0.0.1
├── charenc@0.0.1
└── is-buffer@1.0.2

Any help appreciated.

**Comment by remast** [comment]
Do you get this error on the client or the server side?
Thx

**Comment by wflentje** [comment]
Client.

**Comment by remast** [comment]
Strange. It seems you are missing a JavaScript function on the client to calculate a md5 hashsum. Which browser are you using?

**Comment by remast** [comment]
No answer for a long time so I will close it.
