### ISSUE TITLE
team-calendars caching ical request

### ISSUE THREAD

**Issue by jsade** [red6/atlasboard-red6-package#2]
Is there a way to prevent a caching of the ical request? I have a calendar that's constantly updating, but changes are not reflected in the board. The ical file downloaded manually has the updated info, but team-calendars doesn't update it.

**Comment by jsade** [comment]
Any workaround would do, if you have one..

**Comment by remast** [comment]
Actually there is no special cache involved. Every time the calender is loaded it is sent to the client. How often the calendar is loaded depends on the interval specified in the dashboard configuration. Did you turn on logging to see when the calender is loaded on both client and server side?

**Comment by jsade** [comment]
Ah, the issue was related to [this bug](https://github.com/peterbraden/ical.js/issues/45), that has since been fixed. Removing the old workaround fixed my issue.
